### ISSUE TITLE
RuntimeWarning(err): line 76, in _post

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/py-whitefacesdk#13]
When trying to submit email data to the UCE feed, I am seeing this error. <see below> It is unclear to me from the SDK output what the problem is. 

Running the most recently version of the whiteface sdk as of this [commit](https://github.com/csirtgadgets/py-whitefacesdk/commit/e05b65170c81ac44eb1e208698e09ecee6f0f2ca)

```
$ cat email.eml | /opt/py-cgmail/venv/bin/python2.7 whiteface-submit.py 
2015-11-02 15:36:15,036 - INFO - __main__[64] - processing email
2015-11-02 15:36:15,045 - INFO - requests.packages.urllib3.connectionpool[756] - ... InsecurePlatformWarning
2015-11-02 15:36:15,094 - ERROR - whiteface.client[75] - None
Traceback (most recent call last):
  File "whiteface-submit.py", line 96, in <module>
    main()
  File "whiteface-submit.py", line 91, in main
    ret = observable.Observable(user=user, feed=feed, token=token, thing=url, tags='uce', comment=comment).new()
  File "/opt/py-cgmail/venv/local/lib/python2.7/site-packages/whiteface/observable.py", line 52, in new
    data = self._post(uri, data)
  File "/opt/py-cgmail/venv/local/lib/python2.7/site-packages/whiteface/client.py", line 76, in _post
    raise RuntimeWarning(err)
RuntimeWarning: None
```

**Comment by giovino** [comment]
closing this, multiple issues: sdk changed, bug upstream.
