### ISSUE TITLE
empty feeds throw errers

### ISSUE THREAD

**Issue by jeffmurphy** [csirtgadgets/py-whitefacesdk#14]
```
$ wf --user a --feed fefef
Traceback (most recent call last):
  File "/usr/local/bin/wf", line 164, in <module>
    sys.exit(main())
  File "/usr/local/bin/wf", line 148, in main
    print Table(data=f.show())
  File "/usr/local/lib/python2.7/dist-packages/whiteface/format/table.py", line 15, in __repr__
    for o in self.data['feed']['observables']:
KeyError: 'observables'
```

**Comment by jeffmurphy** [comment]
fix/14
