### ISSUE TITLE
Improve error of nonexistent user and feed

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/py-whitefacesdk#21]
Improve the error handling of a nonexistent user and non existent feed.

Nonexistent feed:

```
$ wf --user giovino --feed asdf

2015-11-03 10:52:21,618 - ERROR - whitefacesdk.client[65] - None
Traceback (most recent call last):
  File "...py-whitefacesdk/venv/bin/wf", line 9, in <module>
    load_entry_point('whitefacesdk==0-untagged.60.g8941c94', 'console_scripts', 'wf')()
  File "....whitefacesdk/client.py", line 222, in main
    data = Feed(cli).show(options['user'], options['feed'], limit=options['limit'])
  File "....whitefacesdk/feed.py", line 46, in show
    return self.client.get(uri, params={'limit': limit})
  File "/home/giovino/code/py-whitefacesdk/whitefacesdk/client.py", line 46, in get
    return self._get(uri, params=params)
  File "...whitefacesdk/client.py", line 66, in _get
    raise RuntimeWarning(err)
RuntimeWarning: None
```

Nonexistent user:

```
$ wf --user asdf --feed uce-urls

2015-11-03 10:55:56,038 - ERROR - whitefacesdk.client[65] - None
Traceback (most recent call last):
  File "...py-whitefacesdk/venv/bin/wf", line 9, in <module>
    load_entry_point('whitefacesdk==0-untagged.60.g8941c94', 'console_scripts', 'wf')()
  File "...py-whitefacesdk/whitefacesdk/client.py", line 222, in main
    data = Feed(cli).show(options['user'], options['feed'], limit=options['limit'])
  File "...py-whitefacesdk/whitefacesdk/feed.py", line 46, in show
    return self.client.get(uri, params={'limit': limit})
  File "...py-whitefacesdk/whitefacesdk/client.py", line 46, in get
    return self._get(uri, params=params)
  File "...py-whitefacesdk/whitefacesdk/client.py", line 66, in _get
    raise RuntimeWarning(err)
RuntimeWarning: None
```

**Comment by jeffmurphy** [comment]
seems to work now
