### ISSUE TITLE
is upgrading the py-whitefacesdk supported?

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/py-whitefacesdk#45]
If so, it's not...

```
pip install https://github.com/csirtgadgets/py-whitefacesdk/archive/master.tar.gz --upgrade

------------------------------------------------------------
/path/to/wf-ufw/venv/bin/pip run on Tue Nov 24 14:17:09 2015
Downloading/unpacking https://github.com/csirtgadgets/py-whitefacesdk/archive/master.tar.gz
  Downloading from URL https://github.com/csirtgadgets/py-whitefacesdk/archive/master.tar.gz
  Running setup.py (path:/tmp/pip-nVmVLQ-build/setup.py) egg_info for package from https://github.com/csirtgadgets/py-whitefacesdk/archive/master.tar.gz
    running egg_info
    creating pip-egg-info/whitefacesdk.egg-info
    writing requirements to pip-egg-info/whitefacesdk.egg-info/requires.txt
    writing pip-egg-info/whitefacesdk.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/whitefacesdk.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/whitefacesdk.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/whitefacesdk.egg-info/entry_points.txt
    writing manifest file 'pip-egg-info/whitefacesdk.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/whitefacesdk.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/whitefacesdk.egg-info/SOURCES.txt'
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/path/to/wf-ufw/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/path/to/wf-ufw/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/path/to/wf-ufw/venv/local/lib/python2.7/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/path/to/wf-ufw/venv/local/lib/python2.7/site-packages/pip/req.py", line 330, in run_egg_info
    "%(Name)s==%(Version)s" % self.pkg_info())
  File "/path/to/wf-ufw/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/path/to/wf-ufw/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/path/to/wf-ufw/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2583, in scan_list
    "Expected ',' or end-of-list in",line,"at",line[p:]
ValueError: ("Expected ',' or end-of-list in", u'whitefacesdk==0+unknown', 'at', u'+unknown')
```

**Comment by wesyoung** [comment]
try:

```
$ pip install git+https://github.com/csirtgadgets/py-whitefacesdk.git --upgrade
```

i'm guessing it's a side effect of using versioneer to do versioning (by tag) and it doesn't like master atm...

**Comment by wesyoung** [comment]
at-least until we "tag" a release... then i think it'll normalize

**Comment by giovino** [comment]
i'm going to close.. i was unable to fix.. deleted by venv folder and started over.
