### ISSUE TITLE
Python 3: TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/py-whitefacesdk#59]
Look into making the sdk compatiable with Python 3

```
2016-01-12 15:15:58,590 - INFO - requests.packages.urllib3.connectionpool[735] - Starting new HTTPS connection (1): whiteface.csirtgadgets.com
Traceback (most recent call last):
  File "test.py", line 110, in <module>
    main()
  File "test.py", line 105, in main
    'comment': comment
  File "wf-email/venv/lib/python3.4/site-packages/whitefacesdk/indicator.py", line 130, in submit
    return self.client.post(uri, data)
  File "wf-email/venv/lib/python3.4/site-packages/whitefacesdk/client.py", line 126, in post
    body = json.loads(body.content)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

adding .decode() to line 126 in whitefacesdk/client.py addressed this error but more research would need to be done to see what all needs to be done to make this library python 3 compatible. 

```
body = json.loads(body.content.decode())
```

**Comment by giovino** [comment]
test body.text

**Comment by giovino** [comment]
@wesyoung 

body.text does fix / address the issue. My question to you is, do you think it is safe to replace all body.content with body.text?

**Comment by wesyoung** [comment]
Probably but might what to read their api doc to double check the diff.. (Requests)
